name: Run tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run_tests:
    strategy:
      matrix:
        php_version: ["8.4"]
        composer_args: [""]
#         symfony_version: ["6.*", "7.*"]
        symfony_version: ["7.*"]
        include:
            # the oldest supported config
#           - symfony_version: "5.*"
#             php_version: "8.0"
#             # php 8.0 compatible twig has security advisories, --no-blocking needed to install them
#             composer_args: "--prefer-lowest --no-blocking"
#             # the newest supported config
          - symfony_version: "8.*"
            php_version: "8.5"
    runs-on: ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@v3

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.json') }}

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          dev: no
          command: update
          php_version: ${{ matrix.php_version }}
          args: ${{ matrix.composer_args }}
        env:
          SYMFONY_REQUIRE: ${{ matrix.symfony_version }}

      - name: Run tests
        uses: php-actions/phpunit@v4
        with:
          version: "9.6"
          php_version: ${{ matrix.php_version }}
          memory_limit: 512M
          configuration: phpunit.xml.dist
        env:
          APP_ENV: test

